services:
  - type: web
    name: gps-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate --noinput
    startCommand: gunicorn myproject.wsgi:application --bind 0.0.0.0:$PORT --timeout 120
    autoDeploy: true
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: gps-dashboard.onrender.com
      - key: SECRET_KEY
        generateValue: true
